name: Build website

on:
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  push:
    branches: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Installing dependencies
      run: |
        cd tools
        npm install
    - name: Complementing site data
      run: |
        cd tools
        export YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}
        npm run update 2>&1 | tee site-data-collection.log
        grep '[ERROR]' site-data-collection.log > site-data-collection_errors.log || true
        if [ -s  site-data-collection_errors.log ]; then
            echo "::error file=tools/main.js::`tail -n 20 site-data-collection_errors.log`"
            echo ":exclamation: Errors during Complementing site data, please check logs" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            tail -n 20 site-data-collection_errors.log  >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          fi
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.66.0'
        extended: true
    - name: Build website
      run: hugo --minify
