name: Build website

on:
  push:
    branches-ignore:
      - master
      - gh-pages-edit

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      deploy: false
    secrets: inherit   